# Generated by Django 3.0.7 on 2021-03-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_auto_20210315_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
