# Generated by Django 3.0.7 on 2021-03-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0012_subjects_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course_id',
        ),
        migrations.AddField(
            model_name='students',
            name='subject_id',
            field=models.ManyToManyField(to='student_management_app.Subjects'),
        ),
    ]
