# Generated by Django 3.0.7 on 2021-04-02 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0015_auto_20210327_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='subject_id',
            new_name='group_id',
        ),
    ]
