# Generated by Django 3.1.7 on 2021-04-11 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0018_auto_20210411_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.group'),
        ),
    ]
